### PR TITLE
Index card styles fix; Button and Form styles; Form uniformity for update/create

### PR DESCRIPTION
**Pull request by coren-frankel**
This is kind of a beast and I apologize for the size of PR and I intend to retire the indexCardStyle branch after this merge. Please take your time reviewing, I look forward to responding to and amending any issues that arise.

This PR addresses style changes at the component level as well as simple bootstrap class implementations. I will break down the PR file by file:

>CardForm.jsx

1.  The removed code for api post request has migrated to Create.js to make this component reusable.
2. Deconstructs props values for conditional form value rendering
3. 'formSubmitHandler' method has been divided into chunks with new names amongst the views that used CardForm (namely Create.js and Edit.js). 'onSubmitHandler' now prevents default page reloading and lifts the state of the card properties to the view utilizing the form.
4. The remaining changes & majority of new lines are style based--floating label, buttons

>CardList.jsx

1. Removed flipDirection property, allowing it to default to the more appealing 'vertical' flip
2. Adds Edit button to both front and back of flash card, and use pencil-square svg icon from bootstrap to replace text.
3. Implements a onMouseLeave eventListener to each Card on creation, to ensure only one flashcard shows at a time. This method isn't a perfect solution--likely not very mobile friendly, and if you drag the mouse out quick enough you can leave the card description exposed until you mouse back over and out of the card again. That all said, I think this may be functionally sufficient.

>Header.js

1. Adapted styles of the navigation buttons, using bootstrap classes to clean up some CSS.

>index.css

1. Removes uneccessary overflow property, and adapt another per @m-smith15's suggestion: `overflow-x: scroll;
overflow-y: hidden;`
2. Removes unused and redundant CSS properties -- made redundant from bootstrap classes.
3. Some minor indentation changes, some automatic in VSCode; Typo fix

>Create.js

1. Per CardForm change 3, adds axios and useState and migrates createCard function to be passed down the card state and form submission function down to the form through props.
2. Style Back button w/ icon and replace the backToHome function with navigate(-1) to just go back a page--as Home felt like a strange place to go back to from the create card form, especially because the navbar has a big home button.

>Edit.js

1. Adapts the Edit view to use the styled CardForm component and gets a little closer to DRY code.
2. In adapting the form component into this view, the card object was easier to use than its individual properties.
3. Adds a 'loaded' boolean variable to state that binds the form rendering to the GET response.

>Practice.js & ViewAll.js

1. These changes are mostly style-driven, with a couple of text adaptations

How is that for a wall of text for ya? I don't intend to make a habit out of PRs like this. Thank you for your patience reading along. I would be happy to discuss my choices and implementations, and I welcome any comments regarding lack of clarity in code. I'll take those as opportunities to make better comments, and to document better.

### CODE REVIEW

**Comment by coren-frankel** [comment]
I left a typo in index.css, feel free to demand I fix 'aborder' at line 92. 💀

**Comment by m-smith15** [comment]
I fellow student in the art of the wall of text, I see! 

I love the new look and these changes! Lets talk about them either Wednesday or sometime before then. I'm running into some issues when I pull this down that we can discuss

**Comment by coren-frankel** [comment]
Okay, I will try to keep this update brief:

I managed to merge PR #9 into indexCardStyle to retain the git history; A useful learning experience for me. I fixed the bug that stopped the add card form to fail, and in doing so built out the validation messages that were silently failing in a 200 status response before. I tried to keep the styles for the validation messages low-key, I don't have a strong opinion about how they should look, and just gave them a mellow default. I would very much like to step inside the changes with you before we merge

We should discuss solutions to replacing the onMouseLeave trigger for card hiding, and I think [this SO question](https://stackoverflow.com/questions/32553158/detect-click-outside-react-component) has a lot of possible suggestions that we could employ.

Looking forward to cleaning this up and committing smaller chunks. 💩

**Review by m-smith15 — APPROVED** [review]
Looks great! 

Went over this in depth while in our weekly meeting discussing changes and updates. Very solid updates!

**Pull request merged**
