### PR TITLE
Replace all SVG icons with BS icon font

### LINKED ISSUE #21: Replace all Bootstrap SVG icons with icon font HTML elements
After some light research, I found the Bootstrap web font CDN to be a very clean way to use Bootstrap Icons without the clunky SVG elements in the HTML. 

We should add the web font CDN to index.html's head if it is not already done, and replace all bootstrap SVGs with their `<i>` element counterpart from the [Bootstrap](https://icons.getbootstrap.com/) library (i.e. apply `<i class="bi bi-arrow-left-circle"></i>` for the back buttons on Create.js and Edit.js).

This is a good first issue, pretty light if you search for all svgs hiding in the frontend with your IDE. Feel free to comment or reach out to me with questions or suggestions.

### PR DESCRIPTION
**Pull request by Vinitvh**
- Replaced all SVG icons with BS icon font HTML elements so that it's easy for others to follow, and also to tidy up some code.
- closes #21

### CODE REVIEW

**Review by coren-frankel — APPROVED** [review]
Solid work @Vinitvh! I appreciate your attention to detail retaining the margin classes that were applied to a couple of the SVGs.

**Comment by coren-frankel** [comment]
@m-smith15 I approve of this PR, but you still have the permissions required for it to deploy so I will hold off on merging until you can pull those strings.

**Comment by coren-frankel** [comment]
Hey @Vinitvh, while we are awaiting the approval and merge from @m-smith15 would you mind answering a few questions?

1. Are you comfortable with having your LinkedIn shared in all possible places?

2. Are you comfortable with having your Github shared?

3. Ok to share in Github README.md file AND somewhere on the deployed WDF site?

If yes to either, please provide url(s).

Thanks again for jumping onboard! If you have any ideas for features, fixes, or enhancements, please feel free to submit them as issues. Otherwise, we use [this](https://docs.google.com/document/d/1WCxL-ObpanxA-0_K81IMbNgWlwDwPS5SKxNcyhSYlw0/edit) to draft ideas and keep reference to who might want to tackle something. If you provide your email, I would be glad to give you edit access if it's not automatically available.

**Comment by Vinitvh** [comment]
> 

Yes, It's ok for me to share my GitHub profile and as far as LinkedIn goes, I'm not that active there.
- GitHub URL - https://github.com/Vinitvh

**Comment by m-smith15** [comment]
Approving and merging based on @coren-frankel's review! 

@Vinitvh thanks for your work on this! We're asking about GitHub profile b/c we want to add in an "acknowledgements" page in the future to the site. Since you've contributed, you'd be on that page! 

We'll also add your GitHub profile to the contributions section of the readme! Thanks a bunch!

**Review by m-smith15 — APPROVED** [review]
approving based on Coren's feedback

**Comment by Vinitvh** [comment]
@m-smith15 Sounds good. No Issues there. Do let me know if you want me take up any other issue throughout this project course, I would be happy to help.

**Pull request merged**
